import '@/styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en" suppressHydrationWarning>
          <body className="flex flex-col items-center justify-center min-h-dvh min-w-dvw font-sans w-full">
              <main className="grow p-4 h-full flex flex-col justify-center w-full" >
                  {children}
              </main>
          </body>
      </html>
  )
}
